language: node_js

node_js:
  - "4"

notifications:
  email: never

before_install:
- $(! $TRAVIS_SECURE_ENV_VARS) || (openssl aes-256-cbc -K $encrypted_e1ab82f12a98_key -iv $encrypted_e1ab82f12a98_iv
  -in secrets.tar.enc -out secrets.tar -d && tar xvf secrets.tar )
- $(! $TRAVIS_SECURE_ENV_VARS) || ( if [ "$TRAVIS_BRANCH" == "master" ]; then tar xvf secrets-prod.tar; else tar xvf secrets-lab.tar; fi; rm secrets*.tar )

script: npm run build

after_success:
- ./git-lfs.sh
- rm -rf node_modules app/bower_components
- cat /dev/null > dist/bower_components/font-roboto/roboto.html

deploy:
  - provider: gae
    project: coduno
    skip_cleanup: true
    on:
      branch: master
  - provider: gae
    project: coduno-lab
    skip_cleanup: true
    on:
      branch: dev
