language: node_js
node_js:
  - "4"

notifications:
  email: never

before_install:
- $(! $TRAVIS_SECURE_ENV_VARS) || openssl aes-256-cbc -K $encrypted_afa9cea1b82d_key -iv $encrypted_afa9cea1b82d_iv
  -in service-account.json.enc -out service-account.json -d
- npm install --global bower jshint
- bower install
- rm -rf bower_components/prism/tests

script:
- find . -path ./bower_components -prune -o -print | egrep "(html|js|json)$" | xargs jshint --extract=auto

after_success: ./git-lfs.sh

deploy:
  provider: gae
  project: coduno
  skip_cleanup: true
