language: node_js

node_js:
  - "4"

notifications:
  email: never
  slack:
    secure: "0LkOThTlt0eBajVjFlIhu6lu4hfoQZBGvMUPRaUEBoeshTLxfejjWf0VrcyjeOnSiOnVaD2cxadLRfBuX4BMGDks3r5LvbmU1krLQtbhIgpsOr4kEGYveiYqAnnlplMzK6F2cAL4ya4NYp6pKtoDFgVLic7n4P8N6Qp9vaM/3ot3tHrjN6dGHmHpQeUtawJFcFNN2yd9r8ndXWYZ10CFxZPRivNJ+1ZWxKmPpHDCaf19Q1e2viI2msPa25kcDJuEL1aAsgHYsecSSxuyUGt6mwNv+h8lxkTOKfBXYIar8vfRQnJ0eBilYpPbRas4GbZ/u+Q9hGx552AxVrK0qmJkVqmzVIMCmBQY8khRc5Pb8786LPdukHvBG0x6uH0e/2DYege5fEWY8+b3/wic87xVYu3HX7aP08v6NWFKvrUIgnEZ6E6RSFYaKaTL8RJFND4rymr0CtAUe8NWKOsFPkla0eOZCWnXG+fw6V4D5Kxql6UlTILxGI+6znasdBi29/bAZjtsWSEmTRsejnzePBagEofWIAvh1C+392+52cVkvaCxxDHtNPYRrCAz1CMXLeLCNPyC7r4V7Uvp+Ghuxn9xSffBkAI0wuAPzsDD1xsy8Ou/auM91F8AK/cJ8bIz0tjeesFYc4CI7KsELYFXm0Ivn14AnJLD1d+u/3aD2qyC+OU="

before_install:
- $(! $TRAVIS_SECURE_ENV_VARS) || (openssl aes-256-cbc -K $encrypted_e1ab82f12a98_key -iv $encrypted_e1ab82f12a98_iv
  -in secrets.tar.enc -out secrets.tar -d && tar xvf secrets.tar )
- $(! $TRAVIS_SECURE_ENV_VARS) || ( if [ "$TRAVIS_BRANCH" == "master" ]; then tar xvf secrets-prod.tar; else tar xvf secrets-lab.tar; fi; rm secrets*.tar )

script:
- cat /dev/null > app/bower_components/font-roboto/roboto.html
- npm run build

after_success:
- ./git-lfs.sh
- rm -rf node_modules app/bower_components

deploy:
  - provider: gae
    project: coduno
    verbosity: debug
    skip_cleanup: true
    on:
      branch: master
  - provider: gae
    project: coduno-lab
    verbosity: debug
    skip_cleanup: true
    on:
      branch: dev
